### ISSUE TITLE
private key,transation

### ISSUE THREAD

**Issue by simpleshark** [TezosRio/TezosJ_plainJava#5]
How to create a pair of public key and private key,then ,create a transaction use this

**Comment by TezosRio** [comment]
Actually, for security reasons, TezosJ creates the keys automatically under the hood, when you instantiate a new TezosWallet object. So you will never see the keys of a wallet. On the other hand, if you already have a pair of keys, you may create a wallet with them. There is a constructor that uses private and public keys to create a new wallet.

**Comment by simpleshark** [comment]
我没有私钥那我怎么签名，我看到构建交易的时候需要一个enckeys对象，我通过TezosWallet 对象只能拿到地址跟助记词，最后，我无法通过地址跟助记词 new enckeys 对象。
事实上，我更关心怎么用这个工具包创建交易

**Comment by simpleshark** [comment]
I don't have a private key so how do I sign? I see that I need an enckeys object to build the transaction, I can only get the address and mnemonic through the TezosWallet object, and finally, I can't get the address and mnemonic through the new enckeys object.
In fact, I'm more concerned about how do I create transactions with this toolkit

**Comment by simpleshark** [comment]
I don't have a private key so how do I sign? I see that I need an enckeys object to build the transaction, I can only get the address and mnemonic through the TezosWallet object, and finally, I can't get a new enckeys object by the address and mnemonic.
In fact, I'm more concerned about how do I create transactions with this toolkit
